### PR TITLE
Update file-input.html

### PR DESCRIPTION
**Pull request by fredericlefeurmou**
Set the cursor as pointer when the input is hovered
Cf. http://stackoverflow.com/questions/1537223/change-cursor-type-on-input-type-file/24488438#24488438

### CODE REVIEW

**Comment by rnicholus** [comment]
Thanks for the pull request! Which browsers were you able to test out to be sure there were no obvious UI regressions?

**Comment by panuhorsmalahti** [comment]
I would like this to get merged. I can't style the cursor myself because there's no CSS mixin to use.

EDIT: I'm not sure `font-size: 0;` is necessary, though.

**Comment by rnicholus** [comment]
Not sure what you mean by "CSS mixin". Why can't you just target the element or any of its children in your stylesheet?

**Comment by panuhorsmalahti** [comment]
CSS mixins: https://www.polymer-project.org/1.0/docs/devguide/styling#custom-css-mixins

I can't style the children DOM element because it's in the shadow DOM.

**Comment by rnicholus** [comment]
Shadow DOM isn't used by this component. It's just a simple custom element. No need for Polymer here either. Just the webcomponents-lite polyfill for cross-browser support.

**Pull request closed without merging**
