### PR TITLE
Removed Polymer

### PR DESCRIPTION
**Pull request by chris-l**
This solves issue #24

I'm using the snippets I have on my repo at https://github.com/chris-l/vanilla-components-magic to make it vanilla.

However, I must mention that this pull request is only the updated component; that is, I haven't updated the karma tests.

The code is valid according to jshint. And I tested the demo.html and it seems to be working fine.
I tried to keep the number of changed lines at minimum. A lot of the changed lines are only changes in whitespace, but if you check the commit with the [w=1 query argument](https://github.com/chris-l/file-input/commit/11778e96e92b95f241011c4c7054a1952ea24b08?w=1), you'll see only the actual changes.

I hope it can be useful to you, either the way it is, or as starting point for your changes.

And thanks a lot for the great component, is really a better experience to work with this than with `<input type="file">`

### CODE REVIEW

**Comment by chris-l** [comment]
Yeah, travis is failing. Like I mentioned, I didn't updated the karma tests. Haven't investigated yet what is required for that.

**Comment by rnicholus** [comment]
Thanks for your help on this! I meant to take care of #24, but I wasn't clear how many are actually using this web component, and I've been really busy after hours writing a software book (long form version of [this series of blog posts](http://blog.garstasio.com/you-dont-need-jquery/)).

This looks like a good start, and I hope to finish it up after I've released the first 4 chapters of my book, in the next few weeks. 

Note that `<file-input>` works great with [`<form is="ajax-form">`](https://github.com/rnicholus/ajax-form).

**Comment by chris-l** [comment]
"Free yourself from the chains of jQuery"?
hehe, a fellow fan of VanillaJS I see. nice!

**Comment by rnicholus** [comment]
With some of the recent breaking changes to the Shadow DOM spec, and the fact that moving away from polymer requires an undesirable amount of boilerplate in the case of <file-input>, I'm wondering if it's worth the effort to go this route at the moment. My ajax-form element was pretty easy to decouple from polymer, but this is a different beast. Also, unit tests still need to be rewritten. I do like the doc updates you've included though.

**Comment by chris-l** [comment]
Really? I wasn't aware that they did breaking changes! Could you provide a link to read about them?

About making **file-input** a vanilla component or going for another route (which I guess is updating to Polymer 1.0), of course, this is your project, do what you think is best!

I need to use **file-input** on a project that uses Polymer 1.0, so I guess I'll set my fork to be usable as replacement and I'll use it until becomes possible to use this directly under 1.0.

**Comment by rnicholus** [comment]
The specification is still a working draft, so it can change in any way at any time. One of the proposed changes is to the [createShadowRoot](https://github.com/w3c/webcomponents/issues/100) function. The changes are potentially breaking as a mandatory flag param may be a requirement (specifying how open the root is).

**Comment by chris-l** [comment]
ohh. Well, that's not too bad. When/If they actually do it, I'll see how to sniff it on my [vanilla-components-magic](https://github.com/chris-l/vanilla-components-magic).

**Comment by rnicholus** [comment]
I'm thinking the best solution here is for me to update the library to be Polymer 1.x-friendly. I'll open up a case for that. Thanks for all of your help on this!

**Comment by rnicholus** [comment]
Merging this in after all. Staging in the polymer-1.x branch. I'll smooth out any rough edges I run into and attempt to fix the tests. The result will be file-input 2.0.

**Pull request closed without merging**
